### ISSUE TITLE
Add support for hapi v8

### ISSUE THREAD

**Issue by zenorocha** [sandfox/node-hapi-redis#1]
There are couple API differences from hapi `v6.x` to `v8.x`. Would be awesome if this plugin could be updated to the latest hapi version.

**Comment by sandfox** [comment]
Hi @zenorocha 

I've created a new branch https://github.com/sandfox/node-hapi-redis/tree/hapi-v8-compat that I think should work fine with hapi v8 and it's published to npm as version 2.0.0

Let me know if that works for you
