### ISSUE TITLE
location of call to next() causing issues in testing

### ISSUE THREAD

**Issue by jamesdixon** [sandfox/node-hapi-redis#10]
Hi,

I ran into some strange issues while attempting to do acceptance testing while using this plugin. I'm using Lab and `server.inject()` fairly heavily in my tests. Unfortunately, when this plugin is enabled I receive the following error message when running my tests:

`Unhandled rejection TypeError: undefined is not a function` where `undefined` is referencing the `inject()` method of `server`. When looking at `server`, it simply resolves to `{}` rather than an instance of the server. Disabling the plugin allows tests to work properly once again.

After ruling out anything in my tests, I started looking at the plugin itself, specifically [line 35](https://github.com/sandfox/node-hapi-redis/blob/master/index.js#L35) of `index.js` where `next()` is called within `redisClient.on()`. It seems that the placement of this line is causing the server not to be instantiated during tests. If I move it to outside of the block and to the end of the file, it works perfectly. 

All that said, is it absolutely necessary to wait for the client to be 'ready' before calling `next()`? I would think that if there is an error with the client, the error handler will log anything that goes wrong even if the server has moved on to the next plugin. If it's definitely necessary, maybe there is a better option for a fix.

Have you experienced this?

Best,
James

**Comment by jamesdixon** [comment]
Also, here's a sample test where it I get the above error:

``` javascript
const Code = require('code');
const lab = require('lab');
const Lab = exports.lab = lab.script();
const server = require('../../server');
const bookshelf = require('../../config/bookshelf');
const helpers = require('../helpers');

// setup Lab to behave like BDD
const describe = Lab.describe;
const it = Lab.it;
const before = Lab.before;
const after = Lab.after;
const expect = Code.expect;

describe.only('authentication', function() {

  describe('with valid form data', function() {

    it('user can authenticate', function(done) {
      const validOptions = {
        method: 'POST',
        url: '/auth/login',
        payload: {
          email: 'test@gmail.com',
          password: '12345678'
        }
      };

      //authenticate user
      server.inject(validOptions, function(response) {
        expect(response.statusCode).to.equal(200);
        expect(response.result).to.be.instanceOf(Array);
        expect(JSON.stringify(response.result).token).to.exist;
        done();
      });
    });
  });
});
```

FYI, I'm running Node 0.12.2 and Hapi 8.8.1.

**Comment by sandfox** [comment]
Hi James, 

Thanks for this. I'll try and have a look tonight at it in more detail, but the TL:DR is that I decided to make the plugin blocking on redis connection success/failure, but it was a fairly arbitrary decision.

I'm open to making the "blocking-ness" user configurable if it's do-able without too much mess.

**Comment by jamesdixon** [comment]
Hi @sandfox - thanks for getting back to me on this so quickly. Let me know what you think after you take a look. Curious if the configuration will ultimately make a difference. Thanks!

**Comment by sandfox** [comment]
Sorry it's taken a while, not had a lot of free time! 

Rather than add a nonblocking option which I'm in two minds about, I've changed the signature of the module to allow injecting a custom `redis` module for the plugin to use. I admit it's a bit clunky but it's made testing this module a little easier (but I feel there out to be better way, and there probably is).

Hopefully this means you can do something like use `fakeredis` (like I am) for your tests, or if you are feeling adventurous just write your own minimal mock redis lib.

```
var fakeredis = require('fakeredis');

server.register({
      register: require('hapi-redis'),
      options: {redisLibrary: fakeredis}
    }, myCallback)
```

**Comment by jamesdixon** [comment]
Hi, @sandfox. Sorry for the delay on my part as well! I'll give this a try and get back to you as soon as I have some time to implement it. Also, I didn't know about `fakeredis`, so that may be a great step forward. Thanks!

**Comment by jamesdixon** [comment]
@sandfox sorry for the super-long delay on this! Using `fakeredis` with the updated module works great. Thank you!

**Comment by sandfox** [comment]
cool, no worries. Does this mean we can close this issue?
