### ISSUE TITLE
how to register plugin multiple times

### ISSUE THREAD

**Issue by midnightcodr** [sandfox/node-hapi-redis#3]
Hi,
Thanks for the great effort in making the plugin.

I am using hapi 8.4 and in my app I need to make multiple redis connections using this plugin. I am not able to do that because attribute `multiple` is false by default and it's not set in the plugin. The error is

Error: Plugin hapi-redis already registered in http://...

My workaround so far is to modify the plugin by
1) adding attribute `multiple`: `true` to the attributes object
2) turn the exposed key to a variable, i.e.
https://github.com/sandfox/node-hapi-redis/blob/master/index.js#L27 
into
`server.expose(options.client, redisClient);`

and use the plugin in this way:

```
server.register({
    register: require('hapi-redis'),
    options: { client: 'client1', ... }
}, function() {});

server.register({
    register: require('hapi-redis'),
    options: { client: 'client2', ... }
}, function() {});
```

This works however I am not sure this is the correct way to enable multiple connections with hapi-redis. Please advise. Thanks.

**Comment by sandfox** [comment]
Hi @midnightcodr 

After some thought I feel that I should just set the `multiple` attribute to be `true`. If people require strict singleton behaviour then maybe that should be layered in top in another module
