### ISSUE TITLE
Invalid hostname blocks server startup

### ISSUE THREAD

**Issue by djensen47** [sandfox/node-hapi-redis#5]
If the "ready" event is never fired because of an invalid hostname, then `next()` is never invoked and the hapi server does not start.

**Comment by sandfox** [comment]
hmm, good spot. How do you want to go about fixing this? Off the top of my head trapping any error events emitted before we've connected and then calling `next(someError)` seems good.

**Comment by sandfox** [comment]
fixed in #8
