### ISSUE TITLE
Consider renaming?

### ISSUE THREAD

**Issue by dylancwood** [sandfox/node-hapi-redis#9]
@sandfox, Thanks again for this sweet little plugin. One area that I think could be improved is the namespace of the plugin. Since `hapi-redis` is hyphenated, it necessitates the use of `['hapi-redis']` syntax. If the plugin were renamed to `redis` or `hapiredis`, then we could continue to use the more convenient notation. 

I realize that this would be a backwards-compatibility nightmare for your users, so I understand if you're hesitant. Just putting it out there :-)

**Comment by sandfox** [comment]
Hey @dylancwood I have thought about naming stuff before, at one point it seemed to be recommended to name plugins as `hapi-*` for discoverability, but it does mean doing the `['hapi-redis']` referencing as you mention. If npm/hapijs had a good way to do aliasing I'd certainly be up for some kind of change, but as far as I know the npm module name is the only name the plugin gets exported under.

So for the meantime I'd prefer to keep the current name to aid discoverability. I think if I did give it a non-hypenated name I'd go for something totally unrelated to redis (like bassmaster etc)

**Comment by dylancwood** [comment]
Thanks for the reply. One possible solution is to use a custom plugin name instead of the package name. To do this, simply override the package name inside `register.attributes`:

```
exports.register.attributes = {
  pkg: require('./package.json'),
  multiple: true,
  name: 'redis'
};
```

I'll admit that this goes against hapi's recommendations that the plugin name should be the same as the package name. IMO, it is better to have plugin names that are easy to type...

Let me know what you think.

**Comment by sandfox** [comment]
As a compromise how about publishing under 2 names...
I'll make a branch and just change the package name etc and publish it under that and put some stuff in the readme. Whenever updates get made to master I'll just merge them across to the new branch and publish that again?

It's a bit of a work but probably is the path of least surprise?

Which means we need a name for the new module, I'd rather it was something interesting rather than 'hapiredis' :-)

**Comment by dylancwood** [comment]
Hi @sandfox, thank you for willing to be so flexible about this. I've actually brought this up with the Hapi Core project, and they are willing to take a PR from me that will allow user-defined aliases for plugins. This would allow you to publish the `hapi-redis` plugin, and allow me to register it in my project under `plugns.redis`.

I don't know how soon this will be merged in (see PR at https://github.com/hapijs/hapi/pull/2672), but I am willing to wait. If you would still like to create a more simply named sibling package to _hapi-redis_, I am happy to help you come up with names though :-)

**Comment by sandfox** [comment]
Awesome work on that PR. I think thats a far better and wider ranging solution than publishing multiple copies of the same repo. While I'd be up for publishing multiple copies, seeing as it seems your PR has received official blessing and will likely get merged and the current situation isn't ending the world I think I'd rather wait for it to get merged than publish another package and than end up either publishing both for a long time or trying get everyone back onto the original package.
